spring.application.name=backend-api

# ===============================
# CONFIGURACIÓN DE BASE DE DATOS
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/practicadb
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACIÓN DE HIBERNATE/JPA
# ===============================
# create-drop borra y recrea las tablas cada vez que inicias (ideal para desarrollo rápido)
# update solo actualiza las columnas nuevas sin borrar tus datos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true